[package]
name = "k210-example"
version = "0.1.0"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
edition = "2018"

[dependencies]
panic-halt = "0.2.0"
riscv = "0.5.4"
riscv-rt = "0.6.1"
k210-hal = { git = "https://github.com/ketotek/k210-hal", branch = "0.2" }
